language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t eladp75/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true Eladpriel/docker-react npm run test